Add files via upload
itsskey/pySW pull request #1
Opened 2023-10-15 00:12 UTC by itsskey

2023-10-15 14:25 UTC, aeksei requested changes
3.5 из 4 баллов. 

Отличная работа! По тех части вопросов нет, небольшое замечание касательно оформления. 

---
Комментарии делятся на следующие категории:
- `GOOD` - хорошее решение. Хорошее или креативное решение.
- `TODO` - можно лучше. Эти замечания не влияют на оценку, и носят рекомендательный характер.
- `FIXME` - необходимо исправить. Устраните эти замечания, чтобы получить максимальный балл. 

---
После проверки работа, может содержать несколько статусов:
- **Changes requested**. Следует выполнить доработки, чтобы получить максимальный балл.  
	Исправление замечаний следует проводить в IDE и приложить согласно инструкции в этот pull request исправленные файлы. Файлы с исправлениями прикладывайте с теми же названиями!
- **Changes approved**. Работа выполнена на максимальный балл.  
	Рекомендуется учесть комментарии рекомендательного характера, и приложить в этот pull request исправленные файлы. В этом случае повторно на проверку присылать работу не нужно. Можно нажимать зеленую кнопку `Merge pull request`.

2023-10-15 14:25 UTC, aeksei commented on lab/1_1.py
> +sum_ = 0; index_of_none = 0
# FIXME
Это не совсем в стиле python. Лучше на отдельных строках написать.
Сам точку с запятой никогда не использовал))

2023-10-15 14:25 UTC, aeksei commented on lab/1_1.py
> +for i in range(len(numbers)):
# TODO
Касательно текущего решения, пока без объяснений, дойдём до будущих тем, там это будет всё.

`for i in range(count_of_list):` надо заменить на `for i, num in enumerate(numbers):`

2023-10-15 14:25 UTC, aeksei commented on lab/1_1.py
> +        index_of_none = i
# TODO

Тут тоже ок, но если пошли таким путём, можно было бы сохранять все индексы, где стоят пропуски)) Но это на будущее

2023-10-15 14:25 UTC, aeksei commented on lab/1_1.py
0.5 балла

2023-10-15 14:25 UTC, aeksei commented on lab/1_2.py
1 балл

2023-10-15 14:25 UTC, aeksei commented on lab/1_3.py
> +half_of_count = count_of_players // 2
# GOOD

Отличное решение завести переменную, а не пользоваться магическими числами!

2023-10-15 14:25 UTC, aeksei commented on lab/1_3.py
> +print(team_1, team_2, sep='\n')
# TODO

Чтобы не мудрить с `sep='\n'` можно просто вызвать два раза команду `print`

2023-10-15 14:25 UTC, aeksei commented on lab/1_3.py
1 балл

2023-10-15 14:25 UTC, aeksei commented on lab/1_4.py
1 балл

2023-10-16 13:21 UTC, merged

2023-10-16 13:45 UTC, itsskey commented on lab/1_1.py
> +sum_ = 0; index_of_none = 0
```suggestion
sum_ = 0
index_of_none = 0
```